type BrandWebsiteHint = {
  pattern: RegExp;
  domain: string;
};

const BRAND_WEBSITE_HINTS: BrandWebsiteHint[] = [
  { pattern: /sambo kojin/i, domain: "sambokojin.com" },
  { pattern: /food club/i, domain: "foodclub.ph" },
  { pattern: /sitio verde/i, domain: "sitioverdebuffet.com" },
  { pattern: /buffet 101/i, domain: "buffet101.com.ph" },
  { pattern: /jiang nan/i, domain: "jiangnan.com.ph" },
  { pattern: /nabe japanese/i, domain: "nabe.com.ph" },
  { pattern: /namsan korean/i, domain: "namsankoreanbbq.com" },
  { pattern: /yoshimeatsu/i, domain: "yoshimeatsu.com" },
  { pattern: /ramen kuroda/i, domain: "ramenkuroda.com" },
  { pattern: /yabu/i, domain: "yabu.ph" },
  { pattern: /yakiniku like/i, domain: "yakiniku-like.com" },
  { pattern: /lan hot pot/i, domain: "lanhotpot.ph" },
  { pattern: /cafe france/i, domain: "cafefrance.com.ph" },
  { pattern: /bakebe/i, domain: "bakebe.ph" },
  { pattern: /avocadoria/i, domain: "avocadoria.ph" },
  { pattern: /shakey/i, domain: "shakeyspizza.ph" },
  { pattern: /peri-?peri/i, domain: "myperiperi.com" },
  { pattern: /pancake house/i, domain: "pancakehouse.com.ph" },
  { pattern: /the mind museum/i, domain: "themindmuseum.org" },
  { pattern: /dessert museum/i, domain: "thedessertmuseum.com" },
  { pattern: /gootopia/i, domain: "gootopia.ph" },
  { pattern: /art in island/i, domain: "artinisland.com" },
  { pattern: /space.*time cube/i, domain: "spacetimecubemuseum.com" },
  { pattern: /timezone/i, domain: "timezonegames.com" },
  { pattern: /italianni/i, domain: "italiannis.com" },
  { pattern: /dunkin/i, domain: "dunkindonuts.ph" },
  { pattern: /feast and fire/i, domain: "feastandfire.com.ph" },
  { pattern: /blake.*wings/i, domain: "blakes.ph" },
  { pattern: /aldo philippines/i, domain: "aldoshoes.com.ph" },
  { pattern: /royal canin/i, domain: "royalcanin.com" },
  { pattern: /shinagawa/i, domain: "shinagawa.ph" },
  { pattern: /royalcare/i, domain: "royalcare.ph" },
  { pattern: /lakawon/i, domain: "lakawon.ph" },
  { pattern: /seafood paradise|seafood.*ribs/i, domain: "vikings.ph" },
  { pattern: /mccoy/i, domain: "mccoyspizza.com" },
  { pattern: /cyan modern/i, domain: "lansonplace.com" },
  { pattern: /rustan/i, domain: "rustans.com" },
  { pattern: /nustar/i, domain: "nustar.ph" },
  { pattern: /misto|seda/i, domain: "ayalalandhospitality.com" },
  { pattern: /waterfront airport/i, domain: "waterfronthotels.com.ph" },
  { pattern: /goji kitchen/i, domain: "gojikitchenandbarclark.com" },
  { pattern: /malagos/i, domain: "malagos.com" },
  { pattern: /sonya/i, domain: "sonyasgarden.com" },
  { pattern: /true value/i, domain: "truevalue.com.ph" },
  { pattern: /dookki/i, domain: "dookki.com.ph" },
  { pattern: /seattle.*best/i, domain: "seattlesbest.com.ph" },
  { pattern: /diptyque/i, domain: "diptyqueparis.com" },
  { pattern: /inmers/i, domain: "inmers.ph" },
  { pattern: /barenaked/i, domain: "barenaked.ph" },
  { pattern: /premier samgyup/i, domain: "premiersamgyupsal.com" },
  { pattern: /six doors/i, domain: "sixdoors.ph" },
  { pattern: /potato corner|r&b milk|project pie/i, domain: "mysupercard.ph" },
  { pattern: /wong kee/i, domain: "smsupermalls.com" },
  { pattern: /marriott|fairmont|sheraton/i, domain: "marriott.com" },
  { pattern: /crowne plaza/i, domain: "ihg.com" },
  { pattern: /look ph/i, domain: "lookph.com" },
  { pattern: /dads world/i, domain: "dadsmanila.com" },
  { pattern: /cabalen/i, domain: "cabalen.com.ph" },
  { pattern: /samgyupsalamat/i, domain: "samgyupsalamat.com.ph" },
  { pattern: /dohtonbori/i, domain: "dohtonbori.ph" },
];

export function getBrandWebsiteHint(brand: string): string | null {
  const match = BRAND_WEBSITE_HINTS.find((hint) => hint.pattern.test(brand));
  return match?.domain ?? null;
}
