"use client";
// Auto-generated by boneyard vite plugin — do not edit
import { registerBones } from "boneyard-js/react";

import _examples_list from "./examples-list.bones.json";

registerBones({
  "examples-list": _examples_list,
});
